
    //array 
let allImages = [];

for (let i = 0; i < 12; i++) {
    //generate a number and provide to the image to generate randomly
    var generate = Math.floor(Math.random() * 100);
    allImages.push(generate)
    //print the images generated by a random number
    document.getElementById("img").innerHTML += `<div class="col-lg-3 m-4"><img class="img-fluid" style="width : 300px" src="https://source.unsplash.com/random/${generate}x${generate}"></div>`;
}



